/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 86
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 60
#define ALIAS_COUNT 2
#define TOKEN_COUNT 38
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT_PERCENT_PIPE = 1,
  anon_sym_LT_PERCENT_DASH_PIPE = 2,
  anon_sym_LT_PERCENT_PIPE2 = 3,
  anon_sym_LT_PERCENT_DASH_PIPE2 = 4,
  anon_sym_PIPE_PERCENT_GT = 5,
  anon_sym_PIPE_DASH_PERCENT_GT = 6,
  anon_sym_PIPE_PERCENT_GT2 = 7,
  anon_sym_PIPE_DASH_PERCENT_GT2 = 8,
  anon_sym_COMMA = 9,
  anon_sym_EQ = 10,
  sym__parameter_type_name = 11,
  anon_sym_LBRACK = 12,
  anon_sym_RBRACK = 13,
  sym__parameter_type_arg_text = 14,
  anon_sym_LT_PERCENT = 15,
  anon_sym_LT_PERCENT_DASH = 16,
  anon_sym_PERCENT_GT = 17,
  anon_sym_DASH_PERCENT_GT = 18,
  anon_sym_LT_PERCENT_EQ = 19,
  anon_sym_LT_PERCENT_DASH_EQ = 20,
  sym__code_text = 21,
  anon_sym_LT_PERCENT_POUND = 22,
  anon_sym_LT_PERCENT_DASH_POUND = 23,
  sym__comment_text = 24,
  aux_sym_content_token1 = 25,
  anon_sym_LT_PERCENT_PERCENT = 26,
  anon_sym_LT = 27,
  sym_variable = 28,
  sym_class_variable = 29,
  sym_function_call = 30,
  sym__default_atom = 31,
  anon_sym_LPAREN = 32,
  anon_sym_RPAREN = 33,
  anon_sym_LBRACE = 34,
  anon_sym_RBRACE = 35,
  sym__balanced_text = 36,
  sym__ws = 37,
  sym_template = 38,
  sym__template_item = 39,
  sym_parameter_directive = 40,
  sym_parameter_list = 41,
  sym_parameter = 42,
  sym__parameter_type = 43,
  sym__parameter_type_args = 44,
  sym_directive = 45,
  sym_output_directive = 46,
  sym_code = 47,
  sym_comment_directive = 48,
  sym_content = 49,
  aux_sym__default_code = 50,
  sym__balanced_parens = 51,
  sym__balanced_brackets = 52,
  sym__balanced_braces = 53,
  aux_sym_template_repeat1 = 54,
  aux_sym_parameter_list_repeat1 = 55,
  aux_sym__parameter_type_args_repeat1 = 56,
  aux_sym_code_repeat1 = 57,
  aux_sym_content_repeat1 = 58,
  aux_sym__balanced_parens_repeat1 = 59,
  alias_sym_parameter_default = 60,
  alias_sym_parameter_name = 61,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_PERCENT_PIPE] = "<% |",
  [anon_sym_LT_PERCENT_DASH_PIPE] = "<%- |",
  [anon_sym_LT_PERCENT_PIPE2] = "<%|",
  [anon_sym_LT_PERCENT_DASH_PIPE2] = "<%-|",
  [anon_sym_PIPE_PERCENT_GT] = "| %>",
  [anon_sym_PIPE_DASH_PERCENT_GT] = "| -%>",
  [anon_sym_PIPE_PERCENT_GT2] = "|%>",
  [anon_sym_PIPE_DASH_PERCENT_GT2] = "|-%>",
  [anon_sym_COMMA] = ",",
  [anon_sym_EQ] = "=",
  [sym__parameter_type_name] = "_parameter_type_name",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym__parameter_type_arg_text] = "_parameter_type_arg_text",
  [anon_sym_LT_PERCENT] = "<%",
  [anon_sym_LT_PERCENT_DASH] = "<%-",
  [anon_sym_PERCENT_GT] = "%>",
  [anon_sym_DASH_PERCENT_GT] = "-%>",
  [anon_sym_LT_PERCENT_EQ] = "<%=",
  [anon_sym_LT_PERCENT_DASH_EQ] = "<%-=",
  [sym__code_text] = "_code_text",
  [anon_sym_LT_PERCENT_POUND] = "<%#",
  [anon_sym_LT_PERCENT_DASH_POUND] = "<%-#",
  [sym__comment_text] = "comment",
  [aux_sym_content_token1] = "content_token1",
  [anon_sym_LT_PERCENT_PERCENT] = "<%%",
  [anon_sym_LT] = "<",
  [sym_variable] = "variable",
  [sym_class_variable] = "class_variable",
  [sym_function_call] = "function_call",
  [sym__default_atom] = "_default_atom",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym__balanced_text] = "_balanced_text",
  [sym__ws] = "_ws",
  [sym_template] = "template",
  [sym__template_item] = "_template_item",
  [sym_parameter_directive] = "parameter_directive",
  [sym_parameter_list] = "parameter_list",
  [sym_parameter] = "parameter",
  [sym__parameter_type] = "parameter_type",
  [sym__parameter_type_args] = "_parameter_type_args",
  [sym_directive] = "directive",
  [sym_output_directive] = "output_directive",
  [sym_code] = "code",
  [sym_comment_directive] = "comment_directive",
  [sym_content] = "content",
  [aux_sym__default_code] = "_default_code",
  [sym__balanced_parens] = "_balanced_parens",
  [sym__balanced_brackets] = "_balanced_brackets",
  [sym__balanced_braces] = "_balanced_braces",
  [aux_sym_template_repeat1] = "template_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym__parameter_type_args_repeat1] = "_parameter_type_args_repeat1",
  [aux_sym_code_repeat1] = "code_repeat1",
  [aux_sym_content_repeat1] = "content_repeat1",
  [aux_sym__balanced_parens_repeat1] = "_balanced_parens_repeat1",
  [alias_sym_parameter_default] = "parameter_default",
  [alias_sym_parameter_name] = "parameter_name",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_PERCENT_PIPE] = anon_sym_LT_PERCENT_PIPE,
  [anon_sym_LT_PERCENT_DASH_PIPE] = anon_sym_LT_PERCENT_DASH_PIPE,
  [anon_sym_LT_PERCENT_PIPE2] = anon_sym_LT_PERCENT_PIPE2,
  [anon_sym_LT_PERCENT_DASH_PIPE2] = anon_sym_LT_PERCENT_DASH_PIPE2,
  [anon_sym_PIPE_PERCENT_GT] = anon_sym_PIPE_PERCENT_GT,
  [anon_sym_PIPE_DASH_PERCENT_GT] = anon_sym_PIPE_DASH_PERCENT_GT,
  [anon_sym_PIPE_PERCENT_GT2] = anon_sym_PIPE_PERCENT_GT2,
  [anon_sym_PIPE_DASH_PERCENT_GT2] = anon_sym_PIPE_DASH_PERCENT_GT2,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym__parameter_type_name] = sym__parameter_type_name,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym__parameter_type_arg_text] = sym__parameter_type_arg_text,
  [anon_sym_LT_PERCENT] = anon_sym_LT_PERCENT,
  [anon_sym_LT_PERCENT_DASH] = anon_sym_LT_PERCENT_DASH,
  [anon_sym_PERCENT_GT] = anon_sym_PERCENT_GT,
  [anon_sym_DASH_PERCENT_GT] = anon_sym_DASH_PERCENT_GT,
  [anon_sym_LT_PERCENT_EQ] = anon_sym_LT_PERCENT_EQ,
  [anon_sym_LT_PERCENT_DASH_EQ] = anon_sym_LT_PERCENT_DASH_EQ,
  [sym__code_text] = sym__code_text,
  [anon_sym_LT_PERCENT_POUND] = anon_sym_LT_PERCENT_POUND,
  [anon_sym_LT_PERCENT_DASH_POUND] = anon_sym_LT_PERCENT_DASH_POUND,
  [sym__comment_text] = sym__comment_text,
  [aux_sym_content_token1] = aux_sym_content_token1,
  [anon_sym_LT_PERCENT_PERCENT] = anon_sym_LT_PERCENT_PERCENT,
  [anon_sym_LT] = anon_sym_LT,
  [sym_variable] = sym_variable,
  [sym_class_variable] = sym_class_variable,
  [sym_function_call] = sym_function_call,
  [sym__default_atom] = sym__default_atom,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym__balanced_text] = sym__balanced_text,
  [sym__ws] = sym__ws,
  [sym_template] = sym_template,
  [sym__template_item] = sym__template_item,
  [sym_parameter_directive] = sym_parameter_directive,
  [sym_parameter_list] = sym_parameter_list,
  [sym_parameter] = sym_parameter,
  [sym__parameter_type] = sym__parameter_type,
  [sym__parameter_type_args] = sym__parameter_type_args,
  [sym_directive] = sym_directive,
  [sym_output_directive] = sym_output_directive,
  [sym_code] = sym_code,
  [sym_comment_directive] = sym_comment_directive,
  [sym_content] = sym_content,
  [aux_sym__default_code] = aux_sym__default_code,
  [sym__balanced_parens] = sym__balanced_parens,
  [sym__balanced_brackets] = sym__balanced_brackets,
  [sym__balanced_braces] = sym__balanced_braces,
  [aux_sym_template_repeat1] = aux_sym_template_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym__parameter_type_args_repeat1] = aux_sym__parameter_type_args_repeat1,
  [aux_sym_code_repeat1] = aux_sym_code_repeat1,
  [aux_sym_content_repeat1] = aux_sym_content_repeat1,
  [aux_sym__balanced_parens_repeat1] = aux_sym__balanced_parens_repeat1,
  [alias_sym_parameter_default] = alias_sym_parameter_default,
  [alias_sym_parameter_name] = alias_sym_parameter_name,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_PERCENT_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_PERCENT_DASH_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_PERCENT_PIPE2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_PERCENT_DASH_PIPE2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PERCENT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_DASH_PERCENT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PERCENT_GT2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_DASH_PERCENT_GT2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym__parameter_type_name] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym__parameter_type_arg_text] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_PERCENT_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_PERCENT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_PERCENT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_PERCENT_DASH_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym__code_text] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_PERCENT_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_PERCENT_DASH_POUND] = {
    .visible = true,
    .named = false,
  },
  [sym__comment_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_content_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LT_PERCENT_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_class_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym__default_atom] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym__balanced_text] = {
    .visible = false,
    .named = true,
  },
  [sym__ws] = {
    .visible = false,
    .named = true,
  },
  [sym_template] = {
    .visible = true,
    .named = true,
  },
  [sym__template_item] = {
    .visible = false,
    .named = true,
  },
  [sym_parameter_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym__parameter_type] = {
    .visible = true,
    .named = true,
  },
  [sym__parameter_type_args] = {
    .visible = false,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_output_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_code] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__default_code] = {
    .visible = false,
    .named = false,
  },
  [sym__balanced_parens] = {
    .visible = false,
    .named = true,
  },
  [sym__balanced_brackets] = {
    .visible = false,
    .named = true,
  },
  [sym__balanced_braces] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_template_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__parameter_type_args_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_code_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__balanced_parens_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_parameter_default] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_parameter_name] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_default = 1,
  field_name = 2,
  field_type = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_default] = "default",
  [field_name] = "name",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 3},
  [3] = {.index = 5, .length = 3},
  [4] = {.index = 8, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 2},
    {field_type, 0},
  [2] =
    {field_default, 4},
    {field_name, 2},
    {field_type, 0},
  [5] =
    {field_default, 5},
    {field_name, 2},
    {field_type, 0},
  [8] =
    {field_default, 6},
    {field_name, 2},
    {field_type, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [2] = alias_sym_parameter_name,
  },
  [2] = {
    [2] = alias_sym_parameter_name,
    [4] = alias_sym_parameter_default,
  },
  [3] = {
    [2] = alias_sym_parameter_name,
    [5] = alias_sym_parameter_default,
  },
  [4] = {
    [2] = alias_sym_parameter_name,
    [6] = alias_sym_parameter_default,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  aux_sym__default_code, 2,
    aux_sym__default_code,
    alias_sym_parameter_default,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 35,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 28,
  [41] = 34,
  [42] = 30,
  [43] = 32,
  [44] = 31,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 13,
  [51] = 51,
  [52] = 52,
  [53] = 15,
  [54] = 14,
  [55] = 18,
  [56] = 56,
  [57] = 19,
  [58] = 16,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 66,
  [68] = 68,
  [69] = 65,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 72,
  [82] = 82,
  [83] = 74,
  [84] = 84,
  [85] = 85,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(52);
      ADVANCE_MAP(
        '$', 39,
        '%', 28,
        '(', 95,
        ')', 96,
        ',', 61,
        '-', 13,
        '<', 84,
        '=', 62,
        '[', 65,
        ']', 66,
        '{', 97,
        '|', 1,
        '}', 98,
        '\t', 100,
        '\n', 100,
        '\r', 100,
        ' ', 100,
      );
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(63);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(17);
      if (lookahead == '%') ADVANCE(32);
      if (lookahead == '-') ADVANCE(18);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '"', 5,
        '\'', 20,
        '(', 95,
        ',', 61,
        '[', 65,
        '{', 97,
        '|', 1,
        '\t', 100,
        '\n', 100,
        '\r', 100,
        ' ', 100,
      );
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(64);
      if (lookahead != 0 &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != ']' &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(94);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '"', 5,
        '\'', 20,
        '(', 95,
        '[', 65,
        '{', 97,
        '\t', 100,
        '\n', 100,
        '\r', 100,
        ' ', 100,
      );
      if (lookahead != 0 &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != ',' &&
          lookahead != ']' &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(94);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '\'') ADVANCE(20);
      if (lookahead == '(') ADVANCE(95);
      if (lookahead == '[') ADVANCE(65);
      if (lookahead == '{') ADVANCE(97);
      if (lookahead != 0 &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != ',' &&
          lookahead != ']' &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(94);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(94);
      if (lookahead == '\\') ADVANCE(43);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(99);
      if (lookahead == '\\') ADVANCE(45);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(67);
      if (lookahead == '\\') ADVANCE(47);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      ADVANCE_MAP(
        '"', 6,
        '\'', 21,
        '(', 95,
        ')', 96,
        '[', 65,
        ']', 66,
        '{', 97,
        '}', 98,
      );
      if (lookahead != 0) ADVANCE(99);
      END_STATE();
    case 9:
      if (lookahead == '"') ADVANCE(7);
      if (lookahead == '\'') ADVANCE(22);
      if (lookahead == '[') ADVANCE(65);
      if (lookahead == ']') ADVANCE(66);
      if (lookahead != 0) ADVANCE(67);
      END_STATE();
    case 10:
      if (lookahead == '$') ADVANCE(40);
      if (lookahead == '%') ADVANCE(14);
      if (lookahead == '-') ADVANCE(77);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(100);
      if (lookahead != 0) ADVANCE(76);
      END_STATE();
    case 11:
      if (lookahead == '$') ADVANCE(41);
      END_STATE();
    case 12:
      if (lookahead == '%') ADVANCE(29);
      if (lookahead == '-') ADVANCE(81);
      if (lookahead != 0) ADVANCE(80);
      END_STATE();
    case 13:
      if (lookahead == '%') ADVANCE(30);
      END_STATE();
    case 14:
      if (lookahead == '%') ADVANCE(76);
      if (lookahead == '>') ADVANCE(72);
      if (lookahead != 0) ADVANCE(76);
      END_STATE();
    case 15:
      if (lookahead == '%') ADVANCE(76);
      if (lookahead == '>') ADVANCE(73);
      if (lookahead != 0) ADVANCE(76);
      END_STATE();
    case 16:
      if (lookahead == '%') ADVANCE(76);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(76);
      END_STATE();
    case 17:
      if (lookahead == '%') ADVANCE(33);
      if (lookahead == '-') ADVANCE(19);
      END_STATE();
    case 18:
      if (lookahead == '%') ADVANCE(34);
      END_STATE();
    case 19:
      if (lookahead == '%') ADVANCE(35);
      END_STATE();
    case 20:
      if (lookahead == '\'') ADVANCE(94);
      if (lookahead == '\\') ADVANCE(44);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 21:
      if (lookahead == '\'') ADVANCE(99);
      if (lookahead == '\\') ADVANCE(46);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 22:
      if (lookahead == '\'') ADVANCE(67);
      if (lookahead == '\\') ADVANCE(48);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 23:
      if (lookahead == '(') ADVANCE(24);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 24:
      if (lookahead == ')') ADVANCE(91);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 25:
      if (lookahead == ':') ADVANCE(38);
      END_STATE();
    case 26:
      if (lookahead == ':') ADVANCE(89);
      END_STATE();
    case 27:
      if (lookahead == ':') ADVANCE(90);
      END_STATE();
    case 28:
      if (lookahead == '>') ADVANCE(72);
      END_STATE();
    case 29:
      if (lookahead == '>') ADVANCE(72);
      if (lookahead != 0) ADVANCE(80);
      END_STATE();
    case 30:
      if (lookahead == '>') ADVANCE(73);
      END_STATE();
    case 31:
      if (lookahead == '>') ADVANCE(73);
      if (lookahead != 0) ADVANCE(80);
      END_STATE();
    case 32:
      if (lookahead == '>') ADVANCE(59);
      END_STATE();
    case 33:
      if (lookahead == '>') ADVANCE(57);
      END_STATE();
    case 34:
      if (lookahead == '>') ADVANCE(60);
      END_STATE();
    case 35:
      if (lookahead == '>') ADVANCE(58);
      END_STATE();
    case 36:
      if (lookahead == '|') ADVANCE(53);
      END_STATE();
    case 37:
      if (lookahead == '|') ADVANCE(54);
      END_STATE();
    case 38:
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(63);
      END_STATE();
    case 39:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 40:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (lookahead != 0) ADVANCE(76);
      END_STATE();
    case 41:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 42:
      if (lookahead != 0 &&
          (lookahead < 'A' || 'Z' < lookahead) &&
          lookahead != '_' &&
          (lookahead < 'a' || 'z' < lookahead)) ADVANCE(76);
      END_STATE();
    case 43:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 44:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 45:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(6);
      END_STATE();
    case 46:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(21);
      END_STATE();
    case 47:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(7);
      END_STATE();
    case 48:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(22);
      END_STATE();
    case 49:
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(80);
      END_STATE();
    case 50:
      if (eof) ADVANCE(52);
      if (lookahead == '<') ADVANCE(84);
      if (lookahead != 0) ADVANCE(82);
      END_STATE();
    case 51:
      if (eof) ADVANCE(52);
      if (lookahead == '<') ADVANCE(85);
      if (lookahead != 0) ADVANCE(82);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_PIPE);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_DASH_PIPE);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_PIPE2);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_DASH_PIPE2);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_PIPE_PERCENT_GT);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_PIPE_DASH_PERCENT_GT);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_PIPE_PERCENT_GT2);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_PIPE_DASH_PERCENT_GT2);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym__parameter_type_name);
      if (lookahead == ':') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym__parameter_type_name);
      if (lookahead == ':') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym__parameter_type_arg_text);
      if (lookahead == '"') ADVANCE(7);
      if (lookahead == '\'') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT);
      if (lookahead == ' ') ADVANCE(36);
      if (lookahead == '#') ADVANCE(78);
      if (lookahead == '%') ADVANCE(83);
      if (lookahead == '-') ADVANCE(70);
      if (lookahead == '=') ADVANCE(74);
      if (lookahead == '|') ADVANCE(55);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT);
      if (lookahead == '#') ADVANCE(78);
      if (lookahead == '%') ADVANCE(83);
      if (lookahead == '-') ADVANCE(71);
      if (lookahead == '=') ADVANCE(74);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_DASH);
      if (lookahead == ' ') ADVANCE(37);
      if (lookahead == '#') ADVANCE(79);
      if (lookahead == '=') ADVANCE(75);
      if (lookahead == '|') ADVANCE(56);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_DASH);
      if (lookahead == '#') ADVANCE(79);
      if (lookahead == '=') ADVANCE(75);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_PERCENT_GT);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_DASH_PERCENT_GT);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_EQ);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_DASH_EQ);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym__code_text);
      if (lookahead == '$') ADVANCE(42);
      if (lookahead == '%') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ') ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym__code_text);
      if (lookahead == '$') ADVANCE(42);
      if (lookahead == '%') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ') ADVANCE(76);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_POUND);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_DASH_POUND);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym__comment_text);
      if (lookahead == '%') ADVANCE(49);
      if (lookahead != 0) ADVANCE(80);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym__comment_text);
      if (lookahead == '%') ADVANCE(31);
      if (lookahead != 0) ADVANCE(80);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(aux_sym_content_token1);
      if (lookahead != 0 &&
          lookahead != '<') ADVANCE(82);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_PERCENT);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '%') ADVANCE(68);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '%') ADVANCE(69);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == ':') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_variable);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_class_variable);
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == ':') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(88);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_class_variable);
      if (lookahead == ':') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(88);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_class_variable);
      if (lookahead == ':') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_function_call);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym__default_atom);
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '\'') ADVANCE(20);
      if (lookahead == ':') ADVANCE(93);
      if (lookahead != 0 &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != ',' &&
          lookahead != '[' &&
          lookahead != ']' &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(94);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym__default_atom);
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '\'') ADVANCE(20);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(64);
      if (lookahead != 0 &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != ',' &&
          (lookahead < 'A' || '[' < lookahead) &&
          lookahead != ']' &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(94);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym__default_atom);
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '\'') ADVANCE(20);
      if (lookahead != 0 &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != ',' &&
          lookahead != '[' &&
          lookahead != ']' &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(94);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym__balanced_text);
      if (lookahead == '"') ADVANCE(6);
      if (lookahead == '\'') ADVANCE(21);
      if (lookahead != 0 &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(99);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym__ws);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(100);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 50},
  [2] = {.lex_state = 51},
  [3] = {.lex_state = 51},
  [4] = {.lex_state = 51},
  [5] = {.lex_state = 51},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 51},
  [11] = {.lex_state = 51},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 8},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 51},
  [21] = {.lex_state = 51},
  [22] = {.lex_state = 51},
  [23] = {.lex_state = 51},
  [24] = {.lex_state = 51},
  [25] = {.lex_state = 51},
  [26] = {.lex_state = 51},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 8},
  [29] = {.lex_state = 10},
  [30] = {.lex_state = 8},
  [31] = {.lex_state = 8},
  [32] = {.lex_state = 8},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 8},
  [35] = {.lex_state = 8},
  [36] = {.lex_state = 8},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 10},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 8},
  [41] = {.lex_state = 8},
  [42] = {.lex_state = 8},
  [43] = {.lex_state = 8},
  [44] = {.lex_state = 8},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 10},
  [47] = {.lex_state = 10},
  [48] = {.lex_state = 4},
  [49] = {.lex_state = 4},
  [50] = {.lex_state = 8},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 8},
  [54] = {.lex_state = 8},
  [55] = {.lex_state = 8},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 8},
  [58] = {.lex_state = 8},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 9},
  [66] = {.lex_state = 9},
  [67] = {.lex_state = 9},
  [68] = {.lex_state = 9},
  [69] = {.lex_state = 9},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 9},
  [73] = {.lex_state = 12},
  [74] = {.lex_state = 9},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 11},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_PERCENT_PIPE] = ACTIONS(1),
    [anon_sym_LT_PERCENT_DASH_PIPE] = ACTIONS(1),
    [anon_sym_LT_PERCENT_PIPE2] = ACTIONS(1),
    [anon_sym_LT_PERCENT_DASH_PIPE2] = ACTIONS(1),
    [anon_sym_PIPE_PERCENT_GT] = ACTIONS(1),
    [anon_sym_PIPE_DASH_PERCENT_GT] = ACTIONS(1),
    [anon_sym_PIPE_PERCENT_GT2] = ACTIONS(1),
    [anon_sym_PIPE_DASH_PERCENT_GT2] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym__parameter_type_name] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LT_PERCENT] = ACTIONS(1),
    [anon_sym_LT_PERCENT_DASH] = ACTIONS(1),
    [anon_sym_PERCENT_GT] = ACTIONS(1),
    [anon_sym_DASH_PERCENT_GT] = ACTIONS(1),
    [anon_sym_LT_PERCENT_EQ] = ACTIONS(1),
    [anon_sym_LT_PERCENT_DASH_EQ] = ACTIONS(1),
    [anon_sym_LT_PERCENT_POUND] = ACTIONS(1),
    [anon_sym_LT_PERCENT_DASH_POUND] = ACTIONS(1),
    [anon_sym_LT_PERCENT_PERCENT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [sym_variable] = ACTIONS(1),
    [sym_class_variable] = ACTIONS(1),
    [sym_function_call] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym__ws] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_template] = STATE(82),
    [sym__template_item] = STATE(3),
    [sym_parameter_directive] = STATE(2),
    [sym_directive] = STATE(3),
    [sym_output_directive] = STATE(3),
    [sym_comment_directive] = STATE(3),
    [sym_content] = STATE(3),
    [aux_sym_template_repeat1] = STATE(3),
    [aux_sym_content_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LT_PERCENT_PIPE] = ACTIONS(5),
    [anon_sym_LT_PERCENT_DASH_PIPE] = ACTIONS(5),
    [anon_sym_LT_PERCENT_PIPE2] = ACTIONS(5),
    [anon_sym_LT_PERCENT_DASH_PIPE2] = ACTIONS(5),
    [anon_sym_LT_PERCENT] = ACTIONS(7),
    [anon_sym_LT_PERCENT_DASH] = ACTIONS(7),
    [anon_sym_LT_PERCENT_EQ] = ACTIONS(9),
    [anon_sym_LT_PERCENT_DASH_EQ] = ACTIONS(9),
    [anon_sym_LT_PERCENT_POUND] = ACTIONS(11),
    [anon_sym_LT_PERCENT_DASH_POUND] = ACTIONS(11),
    [aux_sym_content_token1] = ACTIONS(13),
    [anon_sym_LT_PERCENT_PERCENT] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    STATE(10), 1,
      aux_sym_content_repeat1,
    ACTIONS(7), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT_PERCENT_DASH,
    ACTIONS(9), 2,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT_DASH_EQ,
    ACTIONS(11), 2,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_PERCENT_DASH_POUND,
    ACTIONS(13), 2,
      aux_sym_content_token1,
      anon_sym_LT_PERCENT_PERCENT,
    STATE(4), 6,
      sym__template_item,
      sym_directive,
      sym_output_directive,
      sym_comment_directive,
      sym_content,
      aux_sym_template_repeat1,
  [34] = 8,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    STATE(10), 1,
      aux_sym_content_repeat1,
    ACTIONS(7), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT_PERCENT_DASH,
    ACTIONS(9), 2,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT_DASH_EQ,
    ACTIONS(11), 2,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_PERCENT_DASH_POUND,
    ACTIONS(13), 2,
      aux_sym_content_token1,
      anon_sym_LT_PERCENT_PERCENT,
    STATE(5), 6,
      sym__template_item,
      sym_directive,
      sym_output_directive,
      sym_comment_directive,
      sym_content,
      aux_sym_template_repeat1,
  [68] = 8,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    STATE(10), 1,
      aux_sym_content_repeat1,
    ACTIONS(7), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT_PERCENT_DASH,
    ACTIONS(9), 2,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT_DASH_EQ,
    ACTIONS(11), 2,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_PERCENT_DASH_POUND,
    ACTIONS(13), 2,
      aux_sym_content_token1,
      anon_sym_LT_PERCENT_PERCENT,
    STATE(5), 6,
      sym__template_item,
      sym_directive,
      sym_output_directive,
      sym_comment_directive,
      sym_content,
      aux_sym_template_repeat1,
  [102] = 8,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(35), 1,
      anon_sym_LT,
    STATE(10), 1,
      aux_sym_content_repeat1,
    ACTIONS(23), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT_PERCENT_DASH,
    ACTIONS(26), 2,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT_DASH_EQ,
    ACTIONS(29), 2,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_PERCENT_DASH_POUND,
    ACTIONS(32), 2,
      aux_sym_content_token1,
      anon_sym_LT_PERCENT_PERCENT,
    STATE(5), 6,
      sym__template_item,
      sym_directive,
      sym_output_directive,
      sym_comment_directive,
      sym_content,
      aux_sym_template_repeat1,
  [136] = 7,
    ACTIONS(40), 1,
      anon_sym_LBRACK,
    ACTIONS(42), 1,
      sym__default_atom,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    ACTIONS(46), 1,
      anon_sym_LBRACE,
    STATE(9), 1,
      aux_sym__default_code,
    STATE(12), 3,
      sym__balanced_parens,
      sym__balanced_brackets,
      sym__balanced_braces,
    ACTIONS(38), 7,
      anon_sym_PIPE_PERCENT_GT,
      anon_sym_PIPE_DASH_PERCENT_GT,
      anon_sym_PIPE_PERCENT_GT2,
      anon_sym_PIPE_DASH_PERCENT_GT2,
      anon_sym_COMMA,
      sym__parameter_type_name,
      sym__ws,
  [166] = 7,
    ACTIONS(40), 1,
      anon_sym_LBRACK,
    ACTIONS(42), 1,
      sym__default_atom,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    ACTIONS(46), 1,
      anon_sym_LBRACE,
    STATE(9), 1,
      aux_sym__default_code,
    STATE(12), 3,
      sym__balanced_parens,
      sym__balanced_brackets,
      sym__balanced_braces,
    ACTIONS(48), 7,
      anon_sym_PIPE_PERCENT_GT,
      anon_sym_PIPE_DASH_PERCENT_GT,
      anon_sym_PIPE_PERCENT_GT2,
      anon_sym_PIPE_DASH_PERCENT_GT2,
      anon_sym_COMMA,
      sym__parameter_type_name,
      sym__ws,
  [196] = 7,
    ACTIONS(40), 1,
      anon_sym_LBRACK,
    ACTIONS(42), 1,
      sym__default_atom,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    ACTIONS(46), 1,
      anon_sym_LBRACE,
    STATE(9), 1,
      aux_sym__default_code,
    STATE(12), 3,
      sym__balanced_parens,
      sym__balanced_brackets,
      sym__balanced_braces,
    ACTIONS(50), 7,
      anon_sym_PIPE_PERCENT_GT,
      anon_sym_PIPE_DASH_PERCENT_GT,
      anon_sym_PIPE_PERCENT_GT2,
      anon_sym_PIPE_DASH_PERCENT_GT2,
      anon_sym_COMMA,
      sym__parameter_type_name,
      sym__ws,
  [226] = 7,
    ACTIONS(54), 1,
      anon_sym_LBRACK,
    ACTIONS(57), 1,
      sym__default_atom,
    ACTIONS(60), 1,
      anon_sym_LPAREN,
    ACTIONS(63), 1,
      anon_sym_LBRACE,
    STATE(9), 1,
      aux_sym__default_code,
    STATE(12), 3,
      sym__balanced_parens,
      sym__balanced_brackets,
      sym__balanced_braces,
    ACTIONS(52), 7,
      anon_sym_PIPE_PERCENT_GT,
      anon_sym_PIPE_DASH_PERCENT_GT,
      anon_sym_PIPE_PERCENT_GT2,
      anon_sym_PIPE_DASH_PERCENT_GT2,
      anon_sym_COMMA,
      sym__parameter_type_name,
      sym__ws,
  [256] = 5,
    ACTIONS(72), 1,
      anon_sym_LT,
    STATE(11), 1,
      aux_sym_content_repeat1,
    ACTIONS(68), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT_PERCENT_DASH,
    ACTIONS(70), 2,
      aux_sym_content_token1,
      anon_sym_LT_PERCENT_PERCENT,
    ACTIONS(66), 5,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT_DASH_EQ,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_PERCENT_DASH_POUND,
  [278] = 5,
    ACTIONS(81), 1,
      anon_sym_LT,
    STATE(11), 1,
      aux_sym_content_repeat1,
    ACTIONS(76), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT_PERCENT_DASH,
    ACTIONS(78), 2,
      aux_sym_content_token1,
      anon_sym_LT_PERCENT_PERCENT,
    ACTIONS(74), 5,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT_DASH_EQ,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_PERCENT_DASH_POUND,
  [300] = 2,
    ACTIONS(86), 1,
      sym__default_atom,
    ACTIONS(84), 10,
      anon_sym_PIPE_PERCENT_GT,
      anon_sym_PIPE_DASH_PERCENT_GT,
      anon_sym_PIPE_PERCENT_GT2,
      anon_sym_PIPE_DASH_PERCENT_GT2,
      anon_sym_COMMA,
      sym__parameter_type_name,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      sym__ws,
  [316] = 2,
    ACTIONS(90), 1,
      sym__default_atom,
    ACTIONS(88), 10,
      anon_sym_PIPE_PERCENT_GT,
      anon_sym_PIPE_DASH_PERCENT_GT,
      anon_sym_PIPE_PERCENT_GT2,
      anon_sym_PIPE_DASH_PERCENT_GT2,
      anon_sym_COMMA,
      sym__parameter_type_name,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      sym__ws,
  [332] = 2,
    ACTIONS(94), 1,
      sym__default_atom,
    ACTIONS(92), 10,
      anon_sym_PIPE_PERCENT_GT,
      anon_sym_PIPE_DASH_PERCENT_GT,
      anon_sym_PIPE_PERCENT_GT2,
      anon_sym_PIPE_DASH_PERCENT_GT2,
      anon_sym_COMMA,
      sym__parameter_type_name,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      sym__ws,
  [348] = 2,
    ACTIONS(98), 1,
      sym__default_atom,
    ACTIONS(96), 10,
      anon_sym_PIPE_PERCENT_GT,
      anon_sym_PIPE_DASH_PERCENT_GT,
      anon_sym_PIPE_PERCENT_GT2,
      anon_sym_PIPE_DASH_PERCENT_GT2,
      anon_sym_COMMA,
      sym__parameter_type_name,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      sym__ws,
  [364] = 2,
    ACTIONS(102), 1,
      sym__default_atom,
    ACTIONS(100), 10,
      anon_sym_PIPE_PERCENT_GT,
      anon_sym_PIPE_DASH_PERCENT_GT,
      anon_sym_PIPE_PERCENT_GT2,
      anon_sym_PIPE_DASH_PERCENT_GT2,
      anon_sym_COMMA,
      sym__parameter_type_name,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      sym__ws,
  [380] = 6,
    ACTIONS(104), 1,
      anon_sym_LBRACK,
    ACTIONS(109), 1,
      anon_sym_LPAREN,
    ACTIONS(112), 1,
      anon_sym_LBRACE,
    ACTIONS(115), 1,
      sym__balanced_text,
    ACTIONS(107), 3,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
    STATE(17), 4,
      sym__balanced_parens,
      sym__balanced_brackets,
      sym__balanced_braces,
      aux_sym__balanced_parens_repeat1,
  [404] = 2,
    ACTIONS(120), 1,
      sym__default_atom,
    ACTIONS(118), 10,
      anon_sym_PIPE_PERCENT_GT,
      anon_sym_PIPE_DASH_PERCENT_GT,
      anon_sym_PIPE_PERCENT_GT2,
      anon_sym_PIPE_DASH_PERCENT_GT2,
      anon_sym_COMMA,
      sym__parameter_type_name,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      sym__ws,
  [420] = 2,
    ACTIONS(124), 1,
      sym__default_atom,
    ACTIONS(122), 10,
      anon_sym_PIPE_PERCENT_GT,
      anon_sym_PIPE_DASH_PERCENT_GT,
      anon_sym_PIPE_PERCENT_GT2,
      anon_sym_PIPE_DASH_PERCENT_GT2,
      anon_sym_COMMA,
      sym__parameter_type_name,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      sym__ws,
  [436] = 2,
    ACTIONS(128), 3,
      anon_sym_LT_PERCENT,
      anon_sym_LT_PERCENT_DASH,
      anon_sym_LT,
    ACTIONS(126), 7,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT_DASH_EQ,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_PERCENT_DASH_POUND,
      aux_sym_content_token1,
      anon_sym_LT_PERCENT_PERCENT,
  [451] = 2,
    ACTIONS(132), 3,
      anon_sym_LT_PERCENT,
      anon_sym_LT_PERCENT_DASH,
      anon_sym_LT,
    ACTIONS(130), 7,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT_DASH_EQ,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_PERCENT_DASH_POUND,
      aux_sym_content_token1,
      anon_sym_LT_PERCENT_PERCENT,
  [466] = 2,
    ACTIONS(136), 3,
      anon_sym_LT_PERCENT,
      anon_sym_LT_PERCENT_DASH,
      anon_sym_LT,
    ACTIONS(134), 7,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT_DASH_EQ,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_PERCENT_DASH_POUND,
      aux_sym_content_token1,
      anon_sym_LT_PERCENT_PERCENT,
  [481] = 2,
    ACTIONS(140), 3,
      anon_sym_LT_PERCENT,
      anon_sym_LT_PERCENT_DASH,
      anon_sym_LT,
    ACTIONS(138), 7,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT_DASH_EQ,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_PERCENT_DASH_POUND,
      aux_sym_content_token1,
      anon_sym_LT_PERCENT_PERCENT,
  [496] = 2,
    ACTIONS(144), 3,
      anon_sym_LT_PERCENT,
      anon_sym_LT_PERCENT_DASH,
      anon_sym_LT,
    ACTIONS(142), 7,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT_DASH_EQ,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_PERCENT_DASH_POUND,
      aux_sym_content_token1,
      anon_sym_LT_PERCENT_PERCENT,
  [511] = 2,
    ACTIONS(148), 3,
      anon_sym_LT_PERCENT,
      anon_sym_LT_PERCENT_DASH,
      anon_sym_LT,
    ACTIONS(146), 7,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT_DASH_EQ,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_PERCENT_DASH_POUND,
      aux_sym_content_token1,
      anon_sym_LT_PERCENT_PERCENT,
  [526] = 2,
    ACTIONS(152), 3,
      anon_sym_LT_PERCENT,
      anon_sym_LT_PERCENT_DASH,
      anon_sym_LT,
    ACTIONS(150), 7,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT_DASH_EQ,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_PERCENT_DASH_POUND,
      aux_sym_content_token1,
      anon_sym_LT_PERCENT_PERCENT,
  [541] = 6,
    ACTIONS(156), 1,
      sym__parameter_type_name,
    ACTIONS(158), 1,
      sym__ws,
    STATE(37), 1,
      aux_sym_parameter_list_repeat1,
    STATE(51), 1,
      sym_parameter,
    STATE(85), 1,
      sym__parameter_type,
    ACTIONS(154), 4,
      anon_sym_PIPE_PERCENT_GT,
      anon_sym_PIPE_DASH_PERCENT_GT,
      anon_sym_PIPE_PERCENT_GT2,
      anon_sym_PIPE_DASH_PERCENT_GT2,
  [563] = 6,
    ACTIONS(160), 1,
      anon_sym_LBRACK,
    ACTIONS(162), 1,
      anon_sym_RBRACK,
    ACTIONS(164), 1,
      anon_sym_LPAREN,
    ACTIONS(166), 1,
      anon_sym_LBRACE,
    ACTIONS(168), 1,
      sym__balanced_text,
    STATE(30), 4,
      sym__balanced_parens,
      sym__balanced_brackets,
      sym__balanced_braces,
      aux_sym__balanced_parens_repeat1,
  [585] = 5,
    STATE(46), 1,
      aux_sym_code_repeat1,
    STATE(77), 1,
      sym_code,
    ACTIONS(170), 2,
      anon_sym_PERCENT_GT,
      anon_sym_DASH_PERCENT_GT,
    ACTIONS(174), 2,
      sym_variable,
      sym_class_variable,
    ACTIONS(172), 3,
      sym__code_text,
      sym_function_call,
      sym__ws,
  [605] = 6,
    ACTIONS(160), 1,
      anon_sym_LBRACK,
    ACTIONS(164), 1,
      anon_sym_LPAREN,
    ACTIONS(166), 1,
      anon_sym_LBRACE,
    ACTIONS(176), 1,
      anon_sym_RBRACK,
    ACTIONS(178), 1,
      sym__balanced_text,
    STATE(17), 4,
      sym__balanced_parens,
      sym__balanced_brackets,
      sym__balanced_braces,
      aux_sym__balanced_parens_repeat1,
  [627] = 6,
    ACTIONS(160), 1,
      anon_sym_LBRACK,
    ACTIONS(164), 1,
      anon_sym_LPAREN,
    ACTIONS(166), 1,
      anon_sym_LBRACE,
    ACTIONS(178), 1,
      sym__balanced_text,
    ACTIONS(180), 1,
      anon_sym_RBRACE,
    STATE(17), 4,
      sym__balanced_parens,
      sym__balanced_brackets,
      sym__balanced_braces,
      aux_sym__balanced_parens_repeat1,
  [649] = 6,
    ACTIONS(160), 1,
      anon_sym_LBRACK,
    ACTIONS(164), 1,
      anon_sym_LPAREN,
    ACTIONS(166), 1,
      anon_sym_LBRACE,
    ACTIONS(178), 1,
      sym__balanced_text,
    ACTIONS(182), 1,
      anon_sym_RPAREN,
    STATE(17), 4,
      sym__balanced_parens,
      sym__balanced_brackets,
      sym__balanced_braces,
      aux_sym__balanced_parens_repeat1,
  [671] = 7,
    ACTIONS(40), 1,
      anon_sym_LBRACK,
    ACTIONS(42), 1,
      sym__default_atom,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    ACTIONS(46), 1,
      anon_sym_LBRACE,
    ACTIONS(184), 1,
      sym__ws,
    STATE(7), 1,
      aux_sym__default_code,
    STATE(12), 3,
      sym__balanced_parens,
      sym__balanced_brackets,
      sym__balanced_braces,
  [695] = 6,
    ACTIONS(160), 1,
      anon_sym_LBRACK,
    ACTIONS(164), 1,
      anon_sym_LPAREN,
    ACTIONS(166), 1,
      anon_sym_LBRACE,
    ACTIONS(186), 1,
      anon_sym_RPAREN,
    ACTIONS(188), 1,
      sym__balanced_text,
    STATE(32), 4,
      sym__balanced_parens,
      sym__balanced_brackets,
      sym__balanced_braces,
      aux_sym__balanced_parens_repeat1,
  [717] = 6,
    ACTIONS(160), 1,
      anon_sym_LBRACK,
    ACTIONS(164), 1,
      anon_sym_LPAREN,
    ACTIONS(166), 1,
      anon_sym_LBRACE,
    ACTIONS(190), 1,
      anon_sym_RBRACE,
    ACTIONS(192), 1,
      sym__balanced_text,
    STATE(31), 4,
      sym__balanced_parens,
      sym__balanced_brackets,
      sym__balanced_braces,
      aux_sym__balanced_parens_repeat1,
  [739] = 6,
    ACTIONS(160), 1,
      anon_sym_LBRACK,
    ACTIONS(164), 1,
      anon_sym_LPAREN,
    ACTIONS(166), 1,
      anon_sym_LBRACE,
    ACTIONS(194), 1,
      anon_sym_RBRACE,
    ACTIONS(196), 1,
      sym__balanced_text,
    STATE(44), 4,
      sym__balanced_parens,
      sym__balanced_brackets,
      sym__balanced_braces,
      aux_sym__balanced_parens_repeat1,
  [761] = 6,
    ACTIONS(200), 1,
      sym__parameter_type_name,
    ACTIONS(203), 1,
      sym__ws,
    STATE(37), 1,
      aux_sym_parameter_list_repeat1,
    STATE(51), 1,
      sym_parameter,
    STATE(85), 1,
      sym__parameter_type,
    ACTIONS(198), 4,
      anon_sym_PIPE_PERCENT_GT,
      anon_sym_PIPE_DASH_PERCENT_GT,
      anon_sym_PIPE_PERCENT_GT2,
      anon_sym_PIPE_DASH_PERCENT_GT2,
  [783] = 5,
    STATE(46), 1,
      aux_sym_code_repeat1,
    STATE(76), 1,
      sym_code,
    ACTIONS(174), 2,
      sym_variable,
      sym_class_variable,
    ACTIONS(206), 2,
      anon_sym_PERCENT_GT,
      anon_sym_DASH_PERCENT_GT,
    ACTIONS(172), 3,
      sym__code_text,
      sym_function_call,
      sym__ws,
  [803] = 7,
    ACTIONS(40), 1,
      anon_sym_LBRACK,
    ACTIONS(42), 1,
      sym__default_atom,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    ACTIONS(46), 1,
      anon_sym_LBRACE,
    ACTIONS(208), 1,
      sym__ws,
    STATE(8), 1,
      aux_sym__default_code,
    STATE(12), 3,
      sym__balanced_parens,
      sym__balanced_brackets,
      sym__balanced_braces,
  [827] = 6,
    ACTIONS(160), 1,
      anon_sym_LBRACK,
    ACTIONS(164), 1,
      anon_sym_LPAREN,
    ACTIONS(166), 1,
      anon_sym_LBRACE,
    ACTIONS(210), 1,
      anon_sym_RBRACK,
    ACTIONS(212), 1,
      sym__balanced_text,
    STATE(42), 4,
      sym__balanced_parens,
      sym__balanced_brackets,
      sym__balanced_braces,
      aux_sym__balanced_parens_repeat1,
  [849] = 6,
    ACTIONS(160), 1,
      anon_sym_LBRACK,
    ACTIONS(164), 1,
      anon_sym_LPAREN,
    ACTIONS(166), 1,
      anon_sym_LBRACE,
    ACTIONS(214), 1,
      anon_sym_RPAREN,
    ACTIONS(216), 1,
      sym__balanced_text,
    STATE(43), 4,
      sym__balanced_parens,
      sym__balanced_brackets,
      sym__balanced_braces,
      aux_sym__balanced_parens_repeat1,
  [871] = 6,
    ACTIONS(160), 1,
      anon_sym_LBRACK,
    ACTIONS(164), 1,
      anon_sym_LPAREN,
    ACTIONS(166), 1,
      anon_sym_LBRACE,
    ACTIONS(178), 1,
      sym__balanced_text,
    ACTIONS(218), 1,
      anon_sym_RBRACK,
    STATE(17), 4,
      sym__balanced_parens,
      sym__balanced_brackets,
      sym__balanced_braces,
      aux_sym__balanced_parens_repeat1,
  [893] = 6,
    ACTIONS(160), 1,
      anon_sym_LBRACK,
    ACTIONS(164), 1,
      anon_sym_LPAREN,
    ACTIONS(166), 1,
      anon_sym_LBRACE,
    ACTIONS(178), 1,
      sym__balanced_text,
    ACTIONS(220), 1,
      anon_sym_RPAREN,
    STATE(17), 4,
      sym__balanced_parens,
      sym__balanced_brackets,
      sym__balanced_braces,
      aux_sym__balanced_parens_repeat1,
  [915] = 6,
    ACTIONS(160), 1,
      anon_sym_LBRACK,
    ACTIONS(164), 1,
      anon_sym_LPAREN,
    ACTIONS(166), 1,
      anon_sym_LBRACE,
    ACTIONS(178), 1,
      sym__balanced_text,
    ACTIONS(222), 1,
      anon_sym_RBRACE,
    STATE(17), 4,
      sym__balanced_parens,
      sym__balanced_brackets,
      sym__balanced_braces,
      aux_sym__balanced_parens_repeat1,
  [937] = 3,
    ACTIONS(226), 1,
      anon_sym_EQ,
    ACTIONS(228), 1,
      sym__ws,
    ACTIONS(224), 6,
      anon_sym_PIPE_PERCENT_GT,
      anon_sym_PIPE_DASH_PERCENT_GT,
      anon_sym_PIPE_PERCENT_GT2,
      anon_sym_PIPE_DASH_PERCENT_GT2,
      anon_sym_COMMA,
      sym__parameter_type_name,
  [952] = 4,
    STATE(47), 1,
      aux_sym_code_repeat1,
    ACTIONS(230), 2,
      anon_sym_PERCENT_GT,
      anon_sym_DASH_PERCENT_GT,
    ACTIONS(234), 2,
      sym_variable,
      sym_class_variable,
    ACTIONS(232), 3,
      sym__code_text,
      sym_function_call,
      sym__ws,
  [969] = 4,
    STATE(47), 1,
      aux_sym_code_repeat1,
    ACTIONS(236), 2,
      anon_sym_PERCENT_GT,
      anon_sym_DASH_PERCENT_GT,
    ACTIONS(241), 2,
      sym_variable,
      sym_class_variable,
    ACTIONS(238), 3,
      sym__code_text,
      sym_function_call,
      sym__ws,
  [986] = 6,
    ACTIONS(40), 1,
      anon_sym_LBRACK,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    ACTIONS(46), 1,
      anon_sym_LBRACE,
    ACTIONS(244), 1,
      sym__default_atom,
    STATE(6), 1,
      aux_sym__default_code,
    STATE(12), 3,
      sym__balanced_parens,
      sym__balanced_brackets,
      sym__balanced_braces,
  [1007] = 6,
    ACTIONS(40), 1,
      anon_sym_LBRACK,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    ACTIONS(46), 1,
      anon_sym_LBRACE,
    ACTIONS(244), 1,
      sym__default_atom,
    STATE(8), 1,
      aux_sym__default_code,
    STATE(12), 3,
      sym__balanced_parens,
      sym__balanced_brackets,
      sym__balanced_braces,
  [1028] = 1,
    ACTIONS(88), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym__balanced_text,
  [1038] = 3,
    ACTIONS(248), 1,
      anon_sym_COMMA,
    ACTIONS(250), 1,
      sym__ws,
    ACTIONS(246), 5,
      anon_sym_PIPE_PERCENT_GT,
      anon_sym_PIPE_DASH_PERCENT_GT,
      anon_sym_PIPE_PERCENT_GT2,
      anon_sym_PIPE_DASH_PERCENT_GT2,
      sym__parameter_type_name,
  [1052] = 3,
    ACTIONS(253), 1,
      anon_sym_COMMA,
    ACTIONS(255), 1,
      sym__ws,
    ACTIONS(198), 5,
      anon_sym_PIPE_PERCENT_GT,
      anon_sym_PIPE_DASH_PERCENT_GT,
      anon_sym_PIPE_PERCENT_GT2,
      anon_sym_PIPE_DASH_PERCENT_GT2,
      sym__parameter_type_name,
  [1066] = 1,
    ACTIONS(96), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym__balanced_text,
  [1076] = 1,
    ACTIONS(92), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym__balanced_text,
  [1086] = 1,
    ACTIONS(118), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym__balanced_text,
  [1096] = 4,
    ACTIONS(156), 1,
      sym__parameter_type_name,
    STATE(52), 1,
      sym_parameter,
    STATE(85), 1,
      sym__parameter_type,
    ACTIONS(258), 4,
      anon_sym_PIPE_PERCENT_GT,
      anon_sym_PIPE_DASH_PERCENT_GT,
      anon_sym_PIPE_PERCENT_GT2,
      anon_sym_PIPE_DASH_PERCENT_GT2,
  [1112] = 1,
    ACTIONS(122), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym__balanced_text,
  [1122] = 1,
    ACTIONS(100), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym__balanced_text,
  [1132] = 2,
    ACTIONS(255), 1,
      sym__ws,
    ACTIONS(198), 5,
      anon_sym_PIPE_PERCENT_GT,
      anon_sym_PIPE_DASH_PERCENT_GT,
      anon_sym_PIPE_PERCENT_GT2,
      anon_sym_PIPE_DASH_PERCENT_GT2,
      sym__parameter_type_name,
  [1143] = 6,
    ACTIONS(156), 1,
      sym__parameter_type_name,
    ACTIONS(260), 1,
      sym__ws,
    STATE(27), 1,
      aux_sym_parameter_list_repeat1,
    STATE(51), 1,
      sym_parameter,
    STATE(70), 1,
      sym_parameter_list,
    STATE(85), 1,
      sym__parameter_type,
  [1162] = 2,
    ACTIONS(264), 1,
      sym__ws,
    ACTIONS(262), 5,
      anon_sym_PIPE_PERCENT_GT,
      anon_sym_PIPE_DASH_PERCENT_GT,
      anon_sym_PIPE_PERCENT_GT2,
      anon_sym_PIPE_DASH_PERCENT_GT2,
      sym__parameter_type_name,
  [1173] = 1,
    ACTIONS(262), 6,
      anon_sym_PIPE_PERCENT_GT,
      anon_sym_PIPE_DASH_PERCENT_GT,
      anon_sym_PIPE_PERCENT_GT2,
      anon_sym_PIPE_DASH_PERCENT_GT2,
      sym__parameter_type_name,
      sym__ws,
  [1182] = 1,
    ACTIONS(198), 6,
      anon_sym_PIPE_PERCENT_GT,
      anon_sym_PIPE_DASH_PERCENT_GT,
      anon_sym_PIPE_PERCENT_GT2,
      anon_sym_PIPE_DASH_PERCENT_GT2,
      sym__parameter_type_name,
      sym__ws,
  [1191] = 1,
    ACTIONS(267), 6,
      anon_sym_PIPE_PERCENT_GT,
      anon_sym_PIPE_DASH_PERCENT_GT,
      anon_sym_PIPE_PERCENT_GT2,
      anon_sym_PIPE_DASH_PERCENT_GT2,
      sym__parameter_type_name,
      sym__ws,
  [1200] = 4,
    ACTIONS(269), 1,
      anon_sym_LBRACK,
    ACTIONS(271), 1,
      anon_sym_RBRACK,
    ACTIONS(273), 1,
      sym__parameter_type_arg_text,
    STATE(68), 2,
      sym__parameter_type_args,
      aux_sym__parameter_type_args_repeat1,
  [1214] = 4,
    ACTIONS(269), 1,
      anon_sym_LBRACK,
    ACTIONS(275), 1,
      anon_sym_RBRACK,
    ACTIONS(277), 1,
      sym__parameter_type_arg_text,
    STATE(69), 2,
      sym__parameter_type_args,
      aux_sym__parameter_type_args_repeat1,
  [1228] = 4,
    ACTIONS(269), 1,
      anon_sym_LBRACK,
    ACTIONS(279), 1,
      anon_sym_RBRACK,
    ACTIONS(281), 1,
      sym__parameter_type_arg_text,
    STATE(65), 2,
      sym__parameter_type_args,
      aux_sym__parameter_type_args_repeat1,
  [1242] = 4,
    ACTIONS(283), 1,
      anon_sym_LBRACK,
    ACTIONS(286), 1,
      anon_sym_RBRACK,
    ACTIONS(288), 1,
      sym__parameter_type_arg_text,
    STATE(68), 2,
      sym__parameter_type_args,
      aux_sym__parameter_type_args_repeat1,
  [1256] = 4,
    ACTIONS(269), 1,
      anon_sym_LBRACK,
    ACTIONS(273), 1,
      sym__parameter_type_arg_text,
    ACTIONS(291), 1,
      anon_sym_RBRACK,
    STATE(68), 2,
      sym__parameter_type_args,
      aux_sym__parameter_type_args_repeat1,
  [1270] = 1,
    ACTIONS(293), 4,
      anon_sym_PIPE_PERCENT_GT,
      anon_sym_PIPE_DASH_PERCENT_GT,
      anon_sym_PIPE_PERCENT_GT2,
      anon_sym_PIPE_DASH_PERCENT_GT2,
  [1277] = 3,
    ACTIONS(156), 1,
      sym__parameter_type_name,
    STATE(52), 1,
      sym_parameter,
    STATE(85), 1,
      sym__parameter_type,
  [1287] = 1,
    ACTIONS(295), 3,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym__parameter_type_arg_text,
  [1293] = 2,
    ACTIONS(299), 1,
      sym__comment_text,
    ACTIONS(297), 2,
      anon_sym_PERCENT_GT,
      anon_sym_DASH_PERCENT_GT,
  [1301] = 1,
    ACTIONS(301), 3,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym__parameter_type_arg_text,
  [1307] = 3,
    ACTIONS(303), 1,
      anon_sym_LBRACK,
    ACTIONS(305), 1,
      sym__ws,
    STATE(79), 1,
      sym__parameter_type_args,
  [1317] = 1,
    ACTIONS(307), 2,
      anon_sym_PERCENT_GT,
      anon_sym_DASH_PERCENT_GT,
  [1322] = 1,
    ACTIONS(309), 2,
      anon_sym_PERCENT_GT,
      anon_sym_DASH_PERCENT_GT,
  [1327] = 1,
    ACTIONS(311), 2,
      anon_sym_PERCENT_GT,
      anon_sym_DASH_PERCENT_GT,
  [1332] = 1,
    ACTIONS(313), 1,
      sym__ws,
  [1336] = 1,
    ACTIONS(315), 1,
      sym_variable,
  [1340] = 1,
    ACTIONS(295), 1,
      sym__ws,
  [1344] = 1,
    ACTIONS(317), 1,
      ts_builtin_sym_end,
  [1348] = 1,
    ACTIONS(301), 1,
      sym__ws,
  [1352] = 1,
    ACTIONS(319), 1,
      anon_sym_EQ,
  [1356] = 1,
    ACTIONS(321), 1,
      sym__ws,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 34,
  [SMALL_STATE(4)] = 68,
  [SMALL_STATE(5)] = 102,
  [SMALL_STATE(6)] = 136,
  [SMALL_STATE(7)] = 166,
  [SMALL_STATE(8)] = 196,
  [SMALL_STATE(9)] = 226,
  [SMALL_STATE(10)] = 256,
  [SMALL_STATE(11)] = 278,
  [SMALL_STATE(12)] = 300,
  [SMALL_STATE(13)] = 316,
  [SMALL_STATE(14)] = 332,
  [SMALL_STATE(15)] = 348,
  [SMALL_STATE(16)] = 364,
  [SMALL_STATE(17)] = 380,
  [SMALL_STATE(18)] = 404,
  [SMALL_STATE(19)] = 420,
  [SMALL_STATE(20)] = 436,
  [SMALL_STATE(21)] = 451,
  [SMALL_STATE(22)] = 466,
  [SMALL_STATE(23)] = 481,
  [SMALL_STATE(24)] = 496,
  [SMALL_STATE(25)] = 511,
  [SMALL_STATE(26)] = 526,
  [SMALL_STATE(27)] = 541,
  [SMALL_STATE(28)] = 563,
  [SMALL_STATE(29)] = 585,
  [SMALL_STATE(30)] = 605,
  [SMALL_STATE(31)] = 627,
  [SMALL_STATE(32)] = 649,
  [SMALL_STATE(33)] = 671,
  [SMALL_STATE(34)] = 695,
  [SMALL_STATE(35)] = 717,
  [SMALL_STATE(36)] = 739,
  [SMALL_STATE(37)] = 761,
  [SMALL_STATE(38)] = 783,
  [SMALL_STATE(39)] = 803,
  [SMALL_STATE(40)] = 827,
  [SMALL_STATE(41)] = 849,
  [SMALL_STATE(42)] = 871,
  [SMALL_STATE(43)] = 893,
  [SMALL_STATE(44)] = 915,
  [SMALL_STATE(45)] = 937,
  [SMALL_STATE(46)] = 952,
  [SMALL_STATE(47)] = 969,
  [SMALL_STATE(48)] = 986,
  [SMALL_STATE(49)] = 1007,
  [SMALL_STATE(50)] = 1028,
  [SMALL_STATE(51)] = 1038,
  [SMALL_STATE(52)] = 1052,
  [SMALL_STATE(53)] = 1066,
  [SMALL_STATE(54)] = 1076,
  [SMALL_STATE(55)] = 1086,
  [SMALL_STATE(56)] = 1096,
  [SMALL_STATE(57)] = 1112,
  [SMALL_STATE(58)] = 1122,
  [SMALL_STATE(59)] = 1132,
  [SMALL_STATE(60)] = 1143,
  [SMALL_STATE(61)] = 1162,
  [SMALL_STATE(62)] = 1173,
  [SMALL_STATE(63)] = 1182,
  [SMALL_STATE(64)] = 1191,
  [SMALL_STATE(65)] = 1200,
  [SMALL_STATE(66)] = 1214,
  [SMALL_STATE(67)] = 1228,
  [SMALL_STATE(68)] = 1242,
  [SMALL_STATE(69)] = 1256,
  [SMALL_STATE(70)] = 1270,
  [SMALL_STATE(71)] = 1277,
  [SMALL_STATE(72)] = 1287,
  [SMALL_STATE(73)] = 1293,
  [SMALL_STATE(74)] = 1301,
  [SMALL_STATE(75)] = 1307,
  [SMALL_STATE(76)] = 1317,
  [SMALL_STATE(77)] = 1322,
  [SMALL_STATE(78)] = 1327,
  [SMALL_STATE(79)] = 1332,
  [SMALL_STATE(80)] = 1336,
  [SMALL_STATE(81)] = 1340,
  [SMALL_STATE(82)] = 1344,
  [SMALL_STATE(83)] = 1348,
  [SMALL_STATE(84)] = 1352,
  [SMALL_STATE(85)] = 1356,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 2, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 7, 0, 4),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 5, 0, 2),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 6, 0, 3),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__default_code, 2, 0, 0),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__default_code, 2, 0, 0), SHIFT_REPEAT(28),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__default_code, 2, 0, 0), SHIFT_REPEAT(12),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__default_code, 2, 0, 0), SHIFT_REPEAT(34),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__default_code, 2, 0, 0), SHIFT_REPEAT(35),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_content, 1, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [81] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__default_code, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__default_code, 1, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__balanced_braces, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__balanced_braces, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__balanced_brackets, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__balanced_brackets, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__balanced_parens, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__balanced_parens, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__balanced_brackets, 3, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__balanced_brackets, 3, 0, 0),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__balanced_parens_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__balanced_parens_repeat1, 2, 0, 0),
  [109] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__balanced_parens_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__balanced_parens_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__balanced_parens_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__balanced_parens, 3, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__balanced_parens, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__balanced_braces, 3, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__balanced_braces, 3, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_directive, 2, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_output_directive, 2, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 2, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 2, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_directive, 2, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_directive, 2, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_directive, 3, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_directive, 3, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 3, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 3, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_directive, 3, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_output_directive, 3, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_directive, 3, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_directive, 3, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 1, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0),
  [200] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [203] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, 0, 1),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code, 1, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [234] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_code_repeat1, 2, 0, 0),
  [238] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_code_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [241] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_code_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 1, 0, 0),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [250] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 1, 0, 0), SHIFT_REPEAT(63),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [255] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 3, 0, 0),
  [264] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 3, 0, 0), SHIFT_REPEAT(64),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 4, 0, 0),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [283] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__parameter_type_args_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__parameter_type_args_repeat1, 2, 0, 0),
  [288] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__parameter_type_args_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parameter_type_args, 3, 0, 0),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parameter_type_args, 2, 0, 0),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parameter_type, 1, 0, 0),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [313] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parameter_type, 2, 0, 0),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [317] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_epuppet(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "epuppet",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
